### ISSUE TITLE
OSError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by StephenTellis1** [CandyRoms/candy#14]
Hello i want to download candy rom source and i entered comands as mentioned but it did't work pleade help me out
`stephen@Appu-Pc:~$ **mkdir Candy**
stephen@Appu-Pc:~$ **cd Candy**
stephen@Appu-Pc:~/Candy$ **repo init -u git://github.com/CandyROMs/candy.git -b c10**
warning: gpg (GnuPG) is not available.
warning: Installing it is strongly encouraged.

warning: templates not found /build/git-repo-publish/parts/git/install/usr/share/git-core/templates
Get https://gerrit.googlesource.com/git-repo/clone.bundle
Get https://gerrit.googlesource.com/git-repo
remote: Finding sources: 100% (11/11)
remote: Total 11 (delta 2), reused 11 (delta 2)
Unpacking objects: 100% (11/11), done.
From https://gerrit.googlesource.com/git-repo
   60fc51b..ac29ac3  master     -> origin/master
   dbfbcb1..60fc51b  stable     -> origin/stable
Traceback (most recent call last):
  File "/home/stephen/Candy/.repo/repo/main.py", line 49, in <module>
    import event_log
  File "/home/stephen/Candy/.repo/repo/event_log.py", line 167, in <module>
    _EVENT_ID = multiprocessing.Value('i', 1)
  File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/__init__.py", line 253, in Value
    return Value(typecode_or_type, *args, **kwds)
  File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/sharedctypes.py", line 108, in Value
    lock = RLock()
  File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/__init__.py", line 183, in RLock
    return RLock()
  File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/synchronize.py", line 172, in __init__
    SemLock.__init__(self, RECURSIVE_MUTEX, 1, 1)
  File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied
stephen@Appu-Pc:~/Candy$ **repo sync**
Traceback (most recent call last):
  File "/home/stephen/Candy/.repo/repo/main.py", line 49, in <module>
    import event_log
  File "/home/stephen/Candy/.repo/repo/event_log.py", line 167, in <module>
    _EVENT_ID = multiprocessing.Value('i', 1)
  File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/__init__.py", line 253, in Value
    return Value(typecode_or_type, *args, **kwds)
  File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/sharedctypes.py", line 108, in Value
    lock = RLock()
  File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/__init__.py", line 183, in RLock
    return RLock()
  File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/synchronize.py", line 172, in __init__
    SemLock.__init__(self, RECURSIVE_MUTEX, 1, 1)
  File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied
`

**Comment by pojii** [comment]
please use three back-tick thank you 
```
stephen@Appu-Pc:$ mkdir Candy
stephen@Appu-Pc:$ cd Candy
stephen@Appu-Pc:~/Candy$ repo init -u git://github.com/CandyROMs/candy.git -b c10
warning: gpg (GnuPG) is not available.
warning: Installing it is strongly encouraged.

warning: templates not found /build/git-repo-publish/parts/git/install/usr/share/git-core/templates
Get https://gerrit.googlesource.com/git-repo/clone.bundle
Get https://gerrit.googlesource.com/git-repo
remote: Finding sources: 100% (11/11)
remote: Total 11 (delta 2), reused 11 (delta 2)
Unpacking objects: 100% (11/11), done.
From https://gerrit.googlesource.com/git-repo
60fc51b..ac29ac3 master -> origin/master
dbfbcb1..60fc51b stable -> origin/stable
Traceback (most recent call last):
File "/home/stephen/Candy/.repo/repo/main.py", line 49, in
import event_log
File "/home/stephen/Candy/.repo/repo/event_log.py", line 167, in
_EVENT_ID = multiprocessing.Value('i', 1)
File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/init.py", line 253, in Value
return Value(typecode_or_type, *args, **kwds)
File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/sharedctypes.py", line 108, in Value
lock = RLock()
File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/init.py", line 183, in RLock
return RLock()
File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/synchronize.py", line 172, in init
SemLock.init(self, RECURSIVE_MUTEX, 1, 1)
File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in init
sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied
stephen@Appu-Pc:~/Candy$ repo sync
Traceback (most recent call last):
File "/home/stephen/Candy/.repo/repo/main.py", line 49, in
import event_log
File "/home/stephen/Candy/.repo/repo/event_log.py", line 167, in
_EVENT_ID = multiprocessing.Value('i', 1)
File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/init.py", line 253, in Value
return Value(typecode_or_type, *args, **kwds)
File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/sharedctypes.py", line 108, in Value
lock = RLock()
File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/init.py", line 183, in RLock
return RLock()
File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/synchronize.py", line 172, in init
SemLock.init(self, RECURSIVE_MUTEX, 1, 1)
File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in init
sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied
```

**Comment by NoSpamDan** [comment]
I see this issue is old, but the log output indicates you don't have execute permissions set correctly in your source folder. 

> Hello i want to download candy rom source and i entered comands as mentioned but it did't work pleade help me out
> `stephen@Appu-Pc:~$ **mkdir Candy** stephen@Appu-Pc:~$ **cd Candy**
> stephen@Appu-Pc:~/Candy$ **repo init -u git://github.com/CandyROMs/candy.git -b c10**
> warning: gpg (GnuPG) is not available.
> warning: Installing it is strongly encouraged.
> 
> warning: templates not found /build/git-repo-publish/parts/git/install/usr/share/git-core/templates
> Get [gerrit.googlesource.com/git-repo/clone.bundle](https://gerrit.googlesource.com/git-repo/clone.bundle)
> Get [gerrit.googlesource.com/git-repo](https://gerrit.googlesource.com/git-repo)
> remote: Finding sources: 100% (11/11)
> remote: Total 11 (delta 2), reused 11 (delta 2)
> Unpacking objects: 100% (11/11), done.
> From [gerrit.googlesource.com/git-repo](https://gerrit.googlesource.com/git-repo)
> 60fc51b..ac29ac3 master -> origin/master
> dbfbcb1..60fc51b stable -> origin/stable
> Traceback (most recent call last):
> File "/home/stephen/Candy/.repo/repo/main.py", line 49, in
> import event_log
> File "/home/stephen/Candy/.repo/repo/event_log.py", line 167, in
> _EVENT_ID = multiprocessing.Value('i', 1)
> File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/**init**.py", line 253, in Value
> return Value(typecode_or_type, *args, **kwds)
> File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/sharedctypes.py", line 108, in Value
> lock = RLock()
> File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/**init**.py", line 183, in RLock
> return RLock()
> File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/synchronize.py", line 172, in **init**
> SemLock.**init**(self, RECURSIVE_MUTEX, 1, 1)
> File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in **init**
> sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
> OSError: [Errno 13] Permission denied
> stephen@Appu-Pc:~/Candy$ **repo sync**
> Traceback (most recent call last):
> File "/home/stephen/Candy/.repo/repo/main.py", line 49, in
> import event_log
> File "/home/stephen/Candy/.repo/repo/event_log.py", line 167, in
> _EVENT_ID = multiprocessing.Value('i', 1)
> File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/**init**.py", line 253, in Value
> return Value(typecode_or_type, *args, **kwds)
> File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/sharedctypes.py", line 108, in Value
> lock = RLock()
> File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/**init**.py", line 183, in RLock
> return RLock()
> File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/synchronize.py", line 172, in **init**
> SemLock.**init**(self, RECURSIVE_MUTEX, 1, 1)
> File "/snap/git-repo/18/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in **init**
> sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
> OSError: [Errno 13] Permission denied
> `
